### ISSUE TITLE
Crash when new collection is created

### ISSUE THREAD

**Issue by pascalforny** [FilmColors/VIAN#350]
**To Reproduce**
1. New Collection creation

**Console Log**
Traceback (most recent call last):
  File "C:\Users\Agni\Documents\VIAN\core\gui\main_window.py", line 1136, in on_vocabulary_library_changed
    self.project.sync_with_library(library)
  File "C:\Users\Agni\Documents\VIAN\core\container\project.py", line 1723, in sync_with_library
Mode Import None
(<class 'RecursionError'>, RecursionError('maximum recursion depth exceeded while calling a Python object'), <traceback object at 0x000001A30E3252C8>)
    collection = library.create_collection("Imported from Project {f}".format(f=self.name))
  File "C:\Users\Agni\Documents\VIAN\core\container\vocabulary_library.py", line 138, in create_collection
    self.add_collection(col)
  File "C:\Users\Agni\Documents\VIAN\core\container\vocabulary_library.py", line 149, in add_collection
    self.on_change()
  File "C:\Users\Agni\Documents\VIAN\core\container\vocabulary_library.py", line 110, in on_change
    self.save()
  File "C:\Users\Agni\Documents\VIAN\core\container\vocabulary_library.py", line 188, in save
    json.dump(data, f)
  File "C:\Users\Agni\anaconda3\envs\vian-conda\lib\json\__init__.py", line 180, in dump
    fp.write(chunk)
  File "C:\Users\Agni\anaconda3\envs\vian-conda\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
RecursionError: maximum recursion depth exceeded while calling a Python object

**Comment by flueko** [comment]
Pascal testet
